### PR TITLE
add names of nice people that should not be hacked

### PR DESCRIPTION
**Pull request by odrling**

### CODE REVIEW

**Comment by ggauzin** [comment]
give me write permission or write Matvey pwease

**Comment by odrling** [comment]
@ggauzin done :)

**Comment by ggauzin** [comment]
thx

**Comment by purpurik** [comment]
image
how to fix that?(false)

**Comment by MrHac-ker** [comment]
my discord is jailbreak000 
someone contact me there and help me how to do all this stuff thnks (👍

**Comment by odrling** [comment]
This is not a support thread.
The PR is mostly a joke that I never really expected to see merged, and would at best get a laugh from someone.

**Pull request closed without merging**
